#!/usr/bin/env bash

export PATH=$PATH:~/.guix-profile/libexec

killall pipewire
killall wireplumber

pipewire &
sleep 1
wireplumber &

sleep 1
killall -e xdg-desktop-portal-hyprland
killall -e xdg-desktop-portal-wlr
killall xdg-desktop-portal
xdg-desktop-portal-hyprland &
sleep 2
xdg-desktop-portal &
