#!/usr/bin/env bash

export PATH=$PATH:~/.guix-profile/libexec

sleep 5
killall -e xdg-desktop-portal-hyprland
killall -e xdg-desktop-portal-wlr
killall xdg-desktop-portal
xdg-desktop-portal-hyprland &
sleep 2
xdg-desktop-portal &
